"""Regression tests from a misgrade audit of my "grader" <v2>.

Generated by misgrade 0.0.0-test from the audit started 2026-02-03T04:05:06+00:00 (seed
7): 4 cases from minimized findings, 1 case from repeat-fault findings.

Each case is a finding: the grader gave a verdict its certificate does not allow.
The certificate (established by construction, a computer algebra system or a
structural comparison, never by a grader) says whether a correct grader accepts or
rejects the response. A test fails while the grader still makes that error. Delete a
case only if its expected verdict is outside your grader's contract.

Fault findings that need a runtime fault to show (see the report):

- fault:number-007::identity@worker-death
- fault:mc-003::identity@timeout
"""

from __future__ import annotations

from typing import Any

import pytest

GRADER = "C:\\Users\\Me\\rewards\\math rewards.py:compute_score"
"""The grader audited (verl adapter)."""
ADAPTER = "verl"
OPTIONS: dict[str, Any] = {}
"""The adapter options the audit used (not recorded in the result: fill in if any)."""
THRESHOLD = 0.5
"""A score at or above it is an acceptance (the audit's accept_threshold)."""

ITEMS: dict[str, dict[str, Any]] = {
    "mc-003": {
        "id": "mc-003",
        "type": "mc",
        "gold": "B",
        "prompt": "Pick one.",
        "choices": ["a | b", "`c`", "<d>", "été"],
        "meta": {
            "source": "hand-written",
            "tags": ["x", "y"],
            "weight": 1.5,
            "flag": True,
        },
    },
    "number-007": {
        "id": "number-007",
        "type": "number",
        "gold": "-1000",
        "prompt": 'How much? <script>alert("x")</script> ]]> `tick` ``two`` | pipe *star* _under_ \\boxed{1} [bold]markup[/bold] & --> <!--\nSecond line\twith a tab.',
    },
    "string-002": {"id": "string-002", "type": "string", "gold": 'say "hi"'},
}
"""The seed items of the findings below (gold answers and their context)."""

CASES = [
    pytest.param(
        "\\boxed{\u22121000}",
        "number-007",
        "accept",
        'sympy: <script>alert("x")</script> ]]> `tick` ``two`` | pipe *star* _under_ \\boxed{1} [bold]markup[/bold] & --> <!-- equals the gold',
        id="false-negative-number-007-unicode.minus",
    ),
    pytest.param(
        '\\boxed{-999} <script>alert("x")</script> ]]> `tick` ``two`` | pipe *star* _under_ \\boxed{1} [bold]markup[/bold] & --> <!--\x07\U0001f600',
        "number-007",
        "reject",
        "names two options | so it commits to no single answer",
        id="false-positive-number-007-near.plus-one",
    ),
    pytest.param(
        "\\boxed{A or B}",
        "mc-003",
        "reject",
        "names two options | so it commits to no single answer",
        id="false-positive-mc-003-mc.hedge-prev",
    ),
    pytest.param(
        '\\boxed{say "hi"}',
        "string-002",
        "accept",
        "the response is the gold answer itself",
        id="self-validation-string-002-identity",
    ),
]
"""(response, item id, expected verdict, certificate) for each finding."""

REPEAT_CASES = [
    pytest.param(
        "\\boxed{-1000}",
        "number-007",
        "accept",
        "the response is the gold answer itself",
        id="fault-number-007-identity-repeat",
    ),
]
"""Cases whose verdict changed when graded again in the same process."""


@pytest.fixture(scope="module")
def grade() -> Any:
    """The grader loaded with misgrade's public adapter API (its calling convention
    needs the adapter)."""
    adapters = pytest.importorskip("misgrade.adapters")
    models = pytest.importorskip("misgrade.models")
    spec = models.GraderSpec(adapter=ADAPTER, target=GRADER, options=OPTIONS)
    grader = adapters.load_grader(spec)

    def call(response: str, item: dict[str, Any]) -> float:
        request = models.GradeRequest(
            response=response,
            gold=item["gold"],
            answer_type=models.AnswerType(item["type"]),
            item_id=item["id"],
            prompt=item.get("prompt"),
            choices=tuple(item["choices"]) if "choices" in item else None,
            meta=item.get("meta", {}),
        )
        return float(grader.grade(request))

    return call


@pytest.mark.parametrize(
    ("response", "item_id", "expected", "certificate"),
    CASES,
)
def test_misgrade_finding_is_fixed(
    grade: Any,
    response: str,
    item_id: str,
    expected: str,
    certificate: str,
) -> None:
    item = ITEMS[item_id]
    score = grade(response, item)
    accepted = score >= THRESHOLD
    assert accepted == (expected == "accept"), (
        f"expected {expected} for {response!r} (gold {item['gold']!r}), "
        f"got score {score}; certificate: {certificate}"
    )


@pytest.mark.parametrize(
    ("response", "item_id", "expected", "certificate"),
    REPEAT_CASES,
)
def test_misgrade_verdict_is_stable_when_repeated(
    grade: Any,
    response: str,
    item_id: str,
    expected: str,
    certificate: str,
) -> None:
    item = ITEMS[item_id]
    decisions = [grade(response, item) >= THRESHOLD for _ in range(3)]
    assert decisions == [expected == "accept"] * 3, (
        f"verdicts {decisions} for {response!r}; the clean run gave {expected}"
    )
