"""Regression tests from a misgrade audit of toy.

Generated by misgrade 0.0.0-test from the audit started 2026-01-01T00:00:00+00:00 (seed
0): 2 cases from minimized findings, 1 case from repeat-fault findings.

Each case is a finding: the grader gave a verdict its certificate does not allow.
The certificate (established by construction, a computer algebra system or a
structural comparison, never by a grader) says whether a correct grader accepts or
rejects the response. A test fails while the grader still makes that error. Delete a
case only if its expected verdict is outside your grader's contract.
"""

from __future__ import annotations

import importlib
import importlib.util
import inspect
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pytest

GRADER = "toy_rewards:compute_score"
"""The grader audited (callable adapter)."""
THRESHOLD = 0.5
"""A score at or above it is an acceptance (the audit's accept_threshold)."""

ITEMS: dict[str, dict[str, Any]] = {
    "number-001": {
        "id": "number-001",
        "type": "number",
        "gold": "42",
        "prompt": "6 x 7?",
    },
}
"""The seed items of the findings below (gold answers and their context)."""

CASES = [
    pytest.param(
        "42 ",
        "number-001",
        "accept",
        "appended a space",
        id="false-negative-number-001-ws.trailing-space",
    ),
    pytest.param(
        "43",
        "number-001",
        "reject",
        "43 != 42",
        id="false-positive-number-001-number.plus-one",
    ),
]
"""(response, item id, expected verdict, certificate) for each finding."""

REPEAT_CASES = [
    pytest.param(
        "42",
        "number-001",
        "accept",
        "the response is the gold answer itself",
        id="fault-number-001-identity-repeat",
    ),
]
"""Cases whose verdict changed when graded again in the same process."""


def _load(target: str) -> Any:
    """Import ``module:function``, or load ``path/to/file.py:function``."""
    location, _, name = target.rpartition(":")
    if not location or not name:
        pytest.fail(f"bad GRADER {target!r}: use module:function or file.py:function")
    if location.endswith(".py"):
        here = Path(__file__).resolve().parent
        places = [Path(location), *(base / location for base in (here, *here.parents))]
        path = next((place for place in places if place.is_file()), None)
        if path is None:
            pytest.fail(f"cannot find {location}: edit GRADER at the top of this file")
        sys.path.insert(0, str(path.parent))
        spec = importlib.util.spec_from_file_location(f"_graded_{path.stem}", path)
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
    else:
        module = importlib.import_module(location)
    function: Any = module
    for part in name.split("."):
        function = getattr(function, part)
    return function


def _score(raw: object) -> float:
    """The grader's return value as a score, read the way misgrade reads it."""
    if isinstance(raw, dict) and "score" in raw:
        raw = raw["score"]
    if isinstance(raw, (list, tuple)) and len(raw) == 1:
        raw = raw[0]
    if isinstance(raw, (bool, int, float)):
        return float(raw)
    raise TypeError(f"the grader returned {raw!r}, not a score")


def _keywords(function: Any) -> set[str]:
    """The extra arguments the grader names (the adapter passes them by name)."""
    try:
        parameters = list(inspect.signature(function).parameters.values())
    except (TypeError, ValueError):
        return set()
    kinds = inspect.Parameter
    positional = [p.name for p in parameters if p.kind <= kinds.POSITIONAL_OR_KEYWORD]
    by_name = (kinds.POSITIONAL_OR_KEYWORD, kinds.KEYWORD_ONLY)
    names = {p.name for p in parameters if p.kind in by_name} - set(positional[:2])
    return names & {"prompt", "choices", "meta", "answer_type"}


@pytest.fixture(scope="module")
def grade() -> Callable[[str, dict[str, Any]], float]:
    grader = _load(GRADER)
    wanted = _keywords(grader)

    def call(response: str, item: dict[str, Any]) -> float:
        extras = {
            "prompt": item.get("prompt"),
            "choices": item.get("choices"),
            "meta": item.get("meta", {}),
            "answer_type": item["type"],
        }
        keywords = {name: extras[name] for name in wanted}
        return _score(grader(response, item["gold"], **keywords))

    return call


@pytest.mark.parametrize(
    ("response", "item_id", "expected", "certificate"),
    CASES,
)
def test_misgrade_finding_is_fixed(
    grade: Callable[[str, dict[str, Any]], float],
    response: str,
    item_id: str,
    expected: str,
    certificate: str,
) -> None:
    item = ITEMS[item_id]
    score = grade(response, item)
    accepted = score >= THRESHOLD
    assert accepted == (expected == "accept"), (
        f"expected {expected} for {response!r} (gold {item['gold']!r}), "
        f"got score {score}; certificate: {certificate}"
    )


@pytest.mark.parametrize(
    ("response", "item_id", "expected", "certificate"),
    REPEAT_CASES,
)
def test_misgrade_verdict_is_stable_when_repeated(
    grade: Callable[[str, dict[str, Any]], float],
    response: str,
    item_id: str,
    expected: str,
    certificate: str,
) -> None:
    item = ITEMS[item_id]
    decisions = [grade(response, item) >= THRESHOLD for _ in range(3)]
    assert decisions == [expected == "accept"] * 3, (
        f"verdicts {decisions} for {response!r}; the clean run gave {expected}"
    )
